<?php

namespace Drupal\ejikznayka\Plugin\Field\FieldType;


use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldItemList;

class ScenarioItemList extends FieldItemList {

  public function defaultValuesForm(array &$form, FormStateInterface $form_state) {
    parent::defaultValuesForm($form, $form_state);
  }

  public function defaultValuesFormSubmit(array $element, array &$form, FormStateInterface $form_state) {
    return parent::defaultValuesFormSubmit($element, $form, $form_state); // TODO: Change the autogenerated stub
  }

  public static function processDefaultValue($default_value, FieldableEntityInterface $entity, FieldDefinitionInterface $definition) {
    return parent::processDefaultValue($default_value, $entity, $definition); // TODO: Change the autogenerated stub
  }

}