<?php

namespace Drupal\ejikznayka\Plugin\Field\FieldType;


use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\FieldItemList;

class ScenarioItemList extends FieldItemList {

  public function defaultValuesForm(array &$form, FormStateInterface $form_state) {
    return parent::defaultValuesForm($form, $form_state);
    //return ['#markup' => t('No defaults')];
  }

  public function defaultValuesFormSubmit(array $element, array &$form, FormStateInterface $form_state) {
    return parent::defaultValuesFormSubmit($element, $form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * @inheritDoc
   */
  public function defaultValuesFormValidate(array $element, array &$form, FormStateInterface $form_state) {
    parent::defaultValuesFormValidate($element, $form, $form_state); // TODO: Change the autogenerated stub
    // We set default values just for part of required widget items, so it
    // shouldn't pass normal validation.
    // @Todo Not all errors should be cleared, work more on this
    $form_state->clearErrors();
  }


  public static function processDefaultValue($default_value, FieldableEntityInterface $entity, FieldDefinitionInterface $definition) {
    return parent::processDefaultValue($default_value, $entity, $definition); // TODO: Change the autogenerated stub
  }

  /**
   * Override of FileItemList::defaultValueWidget to use specific widget.
   *
   * @inheritDoc
   */
  protected function defaultValueWidget(FormStateInterface $form_state) {
    if (!$form_state->has('default_value_widget')) {

      // Force a non-required widget.
      $definition = $this->getFieldDefinition();
      $definition->setRequired(FALSE);
      $definition->setDescription('');
      $widget = \Drupal::service('plugin.manager.field.widget')->getInstance([
        'field_definition' => $this->getFieldDefinition(),
        'configuration' => [
          'type' => 'ejikznayka_scenario_default_value',
        ],
      ]);

      $form_state->set('default_value_widget', $widget);
    }

    return $form_state->get('default_value_widget');
  }

}
